services:
  portal:
    container_name: portal
    env_file:
      - .env
    build: .
    expose:
      - ${DENO_PORT:?error}
    networks:
      - private
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:${DENO_PORT:?error} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    attach: false
    security_opt:
      - no-new-privileges:true

networks:
  private:
    name: private
    external: true
